// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prema.ShuleOne.Web.Server.Database;

#nullable disable

namespace Prema.Services.ShuleOneDbManager.Migrations
{
    [DbContext(typeof(ShuleOneDatabaseContext))]
    [Migration("20250323173049_AddedAccountCategories")]
    partial class AddedAccountCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("default_source")
                        .HasColumnType("int");

                    b.Property<int>("fk_account_category_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_account_type_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("default_source")
                        .IsUnique();

                    b.HasIndex("fk_account_category_id");

                    b.HasIndex("fk_account_type_id");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.AccountCategories", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("account_category");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.AccountTypes", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("account_type");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Document", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("document_type")
                        .HasColumnType("int");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fk_created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_student_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fk_student_id");

                    b.ToTable("document");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("fk_created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_employee_bank_details")
                        .HasColumnType("int");

                    b.Property<int>("fk_residence_ward_id")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("kra")
                        .HasColumnType("longtext");

                    b.Property<string>("nssf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("other_names")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("shif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("village_or_estate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_employee_bank_details");

                    b.HasIndex("fk_residence_ward_id");

                    b.ToTable("employee");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.EmployeeBankDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("account_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bank_branch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("employee_bank_details");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.ExpenseType", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("added_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_from_account_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_to_account_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_from_account_id");

                    b.HasIndex("fk_to_account_id");

                    b.ToTable("expense_types");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.FeeType", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("fee_type");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.FileLocationTypes", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("file_location_types");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Grade", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int?>("Teacherid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Teacherid");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.JournalEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fk_account_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_journal_entry_type")
                        .HasColumnType("int");

                    b.Property<int>("fk_transaction_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fk_account_id");

                    b.HasIndex("fk_journal_entry_type");

                    b.HasIndex("fk_transaction_id");

                    b.ToTable("general_ledger");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.JournalEntryTypes", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("journal_entry_type");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.County", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("county");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.Subcounty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("fk_county_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_county_id");

                    b.ToTable("subcounty");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.Ward", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("fk_subcounty_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_subcounty_id");

                    b.ToTable("ward");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.PaymentMethods", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("payment_methods");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Receipt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("file_location")
                        .HasColumnType("longtext");

                    b.Property<int?>("file_location_type")
                        .HasColumnType("int");

                    b.Property<int>("fk_revenue_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_student_id")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fk_revenue_id");

                    b.HasIndex("fk_student_id");

                    b.ToTable("receipt");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.ReceiptItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fk_receipt_id")
                        .HasColumnType("int");

                    b.Property<int>("item_type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fk_receipt_id");

                    b.ToTable("receipt_item");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.ReceiptItemTypes", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("receipt_item_type");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.ReceiptStatuses", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("receipt_status");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Revenue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("account_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("fk_intended_account_number")
                        .HasColumnType("int");

                    b.Property<string>("paid_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("payment_method")
                        .HasColumnType("int");

                    b.Property<string>("payment_reference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("recorded_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("revenue");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.RevenueStatuses", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("revenue_status");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.SMSFailure", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("error")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_sms_record_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fk_sms_record_id");

                    b.ToTable("sms_failure");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.SMSRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_time_sent")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("failure_count")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("recipient_contact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("recipient_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("sms_record");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("admission_status")
                        .HasColumnType("int");

                    b.Property<string>("assessment_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("birth_cert_entry_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("current_grade")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_of_admission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("fk_created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_residence_ward_id")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("medical_needs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("other_names")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("upi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("village_or_estate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_residence_ward_id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.StudentContact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<byte>("contact_priority")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("fk_created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_residence_ward_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_student_id")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("occupation")
                        .HasColumnType("longtext");

                    b.Property<string>("other_names")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("relationship")
                        .HasColumnType("int");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("village_or_estate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_residence_ward_id");

                    b.HasIndex("fk_student_id");

                    b.ToTable("student_contact");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Subject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("fk_transaction_type_identifier")
                        .HasColumnType("int");

                    b.Property<string>("reference_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("transaction_type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.TransactionTypes", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("transaction_type");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.TutionFeesStructure", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_updated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fk_grade_id")
                        .HasColumnType("int");

                    b.Property<int>("term")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_grade_id");

                    b.ToTable("tution_fees_structure");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Teacher", b =>
                {
                    b.HasBaseType("Prema.ShuleOne.Web.Server.Models.Employee");

                    b.Property<string>("highest_qualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("subjects")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tsa_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("teacher");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Account", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.AccountCategories", "AccountCategories")
                        .WithMany()
                        .HasForeignKey("fk_account_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.AccountTypes", "AccountTypes")
                        .WithMany()
                        .HasForeignKey("fk_account_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountCategories");

                    b.Navigation("AccountTypes");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Document", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("fk_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Employee", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.EmployeeBankDetails", "EmployeeBankDetails")
                        .WithMany()
                        .HasForeignKey("fk_employee_bank_details")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Location.Ward", "Ward")
                        .WithMany("Employee")
                        .HasForeignKey("fk_residence_ward_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeBankDetails");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.ExpenseType", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Account", "FromAccount")
                        .WithMany()
                        .HasForeignKey("fk_from_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Account", "ToAccount")
                        .WithMany()
                        .HasForeignKey("fk_to_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromAccount");

                    b.Navigation("ToAccount");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Grade", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Teacher", null)
                        .WithMany("grades")
                        .HasForeignKey("Teacherid");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.JournalEntry", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Account", "Account")
                        .WithMany("JournalEntries")
                        .HasForeignKey("fk_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.JournalEntryTypes", "JournalEntryTypes")
                        .WithMany()
                        .HasForeignKey("fk_journal_entry_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("fk_transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntryTypes");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.Subcounty", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Location.County", "County")
                        .WithMany("Subcounties")
                        .HasForeignKey("fk_county_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.Ward", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Location.Subcounty", "Subcounty")
                        .WithMany("Wards")
                        .HasForeignKey("fk_subcounty_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcounty");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Receipt", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Revenue", "Revenue")
                        .WithMany()
                        .HasForeignKey("fk_revenue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("fk_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revenue");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.ReceiptItem", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Receipt", "Receipt")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("fk_receipt_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.SMSFailure", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.SMSRecord", "SMSRecord")
                        .WithMany("SMSFailures")
                        .HasForeignKey("fk_sms_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SMSRecord");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Student", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Location.Ward", "Ward")
                        .WithMany("Student")
                        .HasForeignKey("fk_residence_ward_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.StudentContact", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Location.Ward", "Ward")
                        .WithMany("StudentContact")
                        .HasForeignKey("fk_residence_ward_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("fk_student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Transaction", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("Accountid");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.TutionFeesStructure", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Grade", "grade")
                        .WithMany()
                        .HasForeignKey("fk_grade_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("grade");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Teacher", b =>
                {
                    b.HasOne("Prema.ShuleOne.Web.Server.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Prema.ShuleOne.Web.Server.Models.Teacher", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Account", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.County", b =>
                {
                    b.Navigation("Subcounties");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.Subcounty", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Location.Ward", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Student");

                    b.Navigation("StudentContact");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Receipt", b =>
                {
                    b.Navigation("ReceiptItems");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.SMSRecord", b =>
                {
                    b.Navigation("SMSFailures");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Student", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Prema.ShuleOne.Web.Server.Models.Teacher", b =>
                {
                    b.Navigation("grades");
                });
#pragma warning restore 612, 618
        }
    }
}
